### ISSUE TITLE
.background modifier with contained shape causes view to expand to full vertical size of the screen

### ISSUE THREAD

**Issue by foscomputerservices** [TokamakUI/Tokamak#402]
When a shape (say a RoundedRectangle()) is added to the background modifier, the view fills the entire vertical height of the screen.

```swift
struct ContentView: View {
    var body: some View {
        Text("Hello, world!")
            .background(RoundedRectangle(cornerRadius: 10.0).fill(Color.red))
    }
}
```

**Expected behavior**

On iOS the background modifier does not change the view size, so I expected the size to remain the size of ```Text```.

**Screenshots**
Attached

<img width="942" alt="Screen Shot 2021-05-14 at 6 06 19 PM" src="https://user-images.githubusercontent.com/2438421/118290619-4ef02600-b4df-11eb-9c12-f6ac53210747.png">

**Workaround**

In this particular example, the following code can be used to work around the issue:

```swift
        Text("Hello, world!")
            .background(Color.red)
            .cornerRadius(10)
```

_NOTE: This issue was previously described along with many other issues in issue #336.  I wanted to provide a contrite example._

**Comment by carson-katri** [comment]
Just dumping this here until I have time to open a PR, but this CSS should be able to fix both `background` and `overlay` layouts:
```css
.zstack {
  display: inline-grid;
  grid-template-columns: auto auto;
}

.foreground {
  grid-area: a;
}

.background {
  /* The interesting part */
  width: 0;
  min-width: 100%;
  height: 0;
  min-height: 100%;
  
  grid-area: a;
  overflow: hidden;
  
  background-color: red;
}
```
[Try it out](https://jsfiddle.net/78etyhsr/)
